# Generated by Django 2.2.1 on 2019-07-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assets.Budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.BooleanField(default=1),
        ),
    ]
