# Generated by Django 2.2.1 on 2019-07-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190713_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='is_output',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='is_output',
        ),
    ]
