# Generated by Django 2.2.1 on 2019-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190718_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_output',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_output',
        ),
        migrations.AddField(
            model_name='expense',
            name='income',
            field=models.BooleanField(default=False),
        ),
    ]
