# Generated by Django 2.2.1 on 2019-07-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_goh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goh',
        ),
    ]
